Header and Homepage
casualbill/cpg-innovation-team-website pull request #3
Opened 2021-06-24 02:01 UTC by lmy0125

完成了最基础的header和公司动态（news）的页面，并对news下的组件进行了不同屏幕大小的适配。
news下前两个按照UI方案使用了card组件但我觉得可能不使用会合适一点，可以讨论。
下一步会对导航栏进行不同屏幕大小的适配（目前只能全屏使用）。

2021-06-24 02:03 UTC, lmy0125 commented
加上了一些routers。

2021-06-25 05:42 UTC, lmy0125 commented
完成最基础的homepage, navbar和project menu。project page一些细节部分未处理（一部分原因是没有具体素材）。navbar也未对小屏幕适配。

2021-06-25 07:11 UTC, casualbill requested changes

2021-06-25 07:11 UTC, casualbill commented on src/components/HeaderNav.vue
> +<style lang="scss">
其他文件也可以看下是否使用 scoped

2021-06-25 07:11 UTC, casualbill commented on src/views/Homepage.vue
> +<style>
scoped

2021-06-25 07:11 UTC, casualbill commented on src/views/ProjectInfo.vue
> +<style lang="scss">
scoped

2021-06-25 07:11 UTC, casualbill commented on src/views/ProjectInfo.vue
> +.col {
看看是不是自定义一个 class 更好

2021-06-25 07:41 UTC, lmy0125 commented on src/views/Homepage.vue
> +#news-header {
那id通常用在什么地方

2021-06-25 07:52 UTC, lmy0125 commented
百度地图的import问题突然没有了，别的问题也解决。

2021-06-25 07:52 UTC, lmy0125 commented on src/views/ProjectInfo.vue
> +.col {
为什么不建议用vuetify自带的class呢？

2021-06-25 08:18 UTC, casualbill commented on src/views/Homepage.vue
> +#news-header {
class多用于标注样式
id多用于锚点，单独元素的事件等

2021-06-25 08:21 UTC, casualbill commented on src/views/ProjectInfo.vue
> +.col {
比如，如果所有 vuetify 的 col 样式都需要改，那你可以直接修改（当然建议在 App.js 中全局修改）
如果你只是在当前页面修改某个样式，建议用自定义 class

2021-06-25 08:30 UTC, casualbill approved these changes

2021-06-25 08:36 UTC, merged